### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by sigita-sevceva** [cmohge1/intro-to-dh#1]
Hi, I have a problem pushing my txt file into this repo, is it open for contributions? Gives me an error: 
`git remote add origin https://github.com/cmohge1/riga-intro-to-dh.git
fatal: remote origin already exists.
git push origin master
fatal: repository 'https://github.com/cmohge1/riga-intro-to-dh/tree/main/texts/' not found`

**Comment by cmohge1** [comment]
Have a look at this documentation. https://kbroman.org/github_tutorial/pages/fork.html
There are basically two options: you either join the repo as a collaborator (which I can do) or you 'fork' the repo (which you do) to merge your repo copy with mine. We can go over this on Friday.

**Comment by cmohge1** [comment]
No worries if that seems too complicated. The idea of the exercise was for you to copy the repo on your local machine and add to it--which it seems you have accomplished. As I said, we will review this on Friday.

**Comment by sigita-sevceva** [comment]
I see, thank you!
